Repository inveniosoftware-contrib/ng2-json-editor, pull requests merged in 2018-02, with the labels that each got.

#456 make the sidebar collapsible
  src/add-field-dropdown/add-field-dropdown.component.html
  src/add-field-dropdown/add-field-dropdown.component.scss
  src/bottom-console-badges/bottom-console-badges.component.html
  src/bottom-console-badges/bottom-console-badges.component.scss
  src/json-editor.component.html
  src/json-editor.component.scss
  src/json-editor.component.ts
  src/object-field/object-field.component.html
  src/table-list-field/table-list-field.component.html
  src/tree-menu/tree-menu.component.scss
Labels: Review: In Review

#462 closes #459
  tslint.json
Labels: Review: WIP

#464 stricter aot compilation
  tsconfig.json
Labels: Review: WIP

#463 add icon in sidebar to toggle preview
  e2e/preview-panel/preview-panel.e2e-spec.ts
  src/bottom-console-badges/bottom-console-badges.component.scss
  src/json-editor.component.html
  src/json-editor.component.scss
Labels: Review: WIP

#468 fix tab when problem at root is clicked
  example/assets/mock-data/problem-map.json
  src/primitive-field/primitive-field.component.ts
  src/shared/services/tabs-util.service.ts
Labels: Review: Ready for Review

#467 fix size of containers and icons
  src/bottom-console-badges/bottom-console-badges.component.scss
  src/json-editor.component.scss
Labels: Review: In Review
